"""Single source of truth for numeric runtime defaults.

Production modules import values from here.  JSON-compatible YAML rule files may
describe behaviour, but do not duplicate these operational limits.
"""

from __future__ import annotations

SCHEMA_VERSION = "1.0"
PRODUCT_VERSION = "0.1.0"
# Stage 0/0.6 measurement used this explicitly identifying, non-browser UA.
USER_AGENT = "dart-search-mcp-stage0-probe/0.1 (local measurement; concurrency=1)"

MIN_TARGET_COUNT = 1
DEFAULT_TARGET_COUNT = 10
INTERACTIVE_TARGET_MAX = 20
BATCH_TARGET_MAX = 500
QUERY_MAX_CHARS = 1000
DOCUMENT_BUDGET_ABSOLUTE_MAX = 120
DOCUMENT_CANDIDATE_HEADROOM_MULTIPLIER = 2
RECEIPT_NO_LENGTH = 14
CORP_CODE_LENGTH = 8
COMPANY_LOOKUP_LIMIT = 20
COMPANY_EXACT_MATCH_LIMIT = 2
LINEAGE_HASH_CHARS = 20

FAST_LIST_REQUEST_BUDGET = 10
FAST_DART_REQUEST_BUDGET = 3
FAST_DOCUMENT_BUDGET = 10
FAST_RESULT_BUDGET = 10
FAST_SOFT_TIMEOUT_SECONDS = 25
FAST_HARD_TIMEOUT_SECONDS = 45

STANDARD_LIST_REQUEST_BUDGET = 40
STANDARD_DART_REQUEST_BUDGET = 10
STANDARD_DOCUMENT_BUDGET = 40
STANDARD_RESULT_BUDGET = 20
STANDARD_PRELIMINARY_BUDGET = 10
STANDARD_SOFT_TIMEOUT_SECONDS = 60
STANDARD_HARD_TIMEOUT_SECONDS = 90
FIRST_CANDIDATE_TARGET_SECONDS = 8
MAX_ESCALATIONS = 2

LIST_CONCURRENCY = 2
DOCUMENT_CONCURRENCY = 3
LOCAL_PARSE_CONCURRENCY = 4
DART_CONCURRENCY = 1
DART_MIN_REQUEST_INTERVAL_SECONDS = 1.0
DART_EFFECTIVE_PAGE_SIZE = 10
DART_FORM_MAX_RESULTS = 15
DART_MAX_LINKS = 10
OPENDART_PAGE_COUNT = 100
OPENDART_WINDOW_MONTHS = 3
OPENDART_COMPANY_BATCH_SIZE = 100
CORPCODE_TTL_HOURS = 24

SESSION_CACHE_MAX_DOCUMENTS = 40
SESSION_CACHE_MAX_TEXT_MB = 64
TTL_DISK_HOURS = 24
TTL_DISK_MAX_SIZE_MB = 500

AMENDMENT_DOCUMENT_BUDGET = 80
AMENDMENT_DOCUMENT_BUDGET_MAX = 120
BATCH_ESTIMATED_DOCUMENT_THRESHOLD = 80
BATCH_ESTIMATED_SECONDS_THRESHOLD = 300
BATCH_RECOMMENDED_CONFIRMATION_MINUTES = 10
CHECKPOINT_RETENTION_DAYS = 7

STRUCTURE_CIRCUIT_SECONDS = 15 * 60
NETWORK_CIRCUIT_SECONDS = 3 * 60
STRUCTURE_FAILURE_THRESHOLD = 2
NETWORK_FAILURE_THRESHOLD = 2

HTTP_TIMEOUT_SECONDS = 20
HTTP_MAX_RETRIES = 2
HTTP_BACKOFF_BASE_SECONDS = 0.5

CONTINUATION_TTL_SECONDS = 30 * 60
CONTINUATION_TOKEN_MAX_LENGTH = 128
AUDIT_RETENTION_DAYS = 30
AUDIT_MAX_SIZE_MB = 50

ZIP_MAX_FILES = 100
ZIP_MAX_SINGLE_FILE_MB = 32
ZIP_MAX_TOTAL_UNCOMPRESSED_MB = 64
ZIP_MAX_COMPRESSION_RATIO = 200
DOCUMENT_MAX_TEXT_MB = 16
EVIDENCE_MAX_SNIPPETS = 8
EVIDENCE_MAX_CHARS = 500
EVIDENCE_PER_CASE = 3
CONTINUATION_TOKEN_RANDOM_BYTES = 18
MIN_FIXED_EVALUATION_QUERIES = 20

DEFAULT_SETTINGS = {
    "schema_version": SCHEMA_VERSION,
    "cache": {
        "session_enabled": True,
        "ttl_disk_enabled": False,
        "ttl_hours": TTL_DISK_HOURS,
        "max_size_mb": TTL_DISK_MAX_SIZE_MB,
    },
    "search": {
        "list_concurrency": LIST_CONCURRENCY,
        "document_concurrency": DOCUMENT_CONCURRENCY,
        "local_parse_concurrency": LOCAL_PARSE_CONCURRENCY,
        "interactive_document_budget": STANDARD_DOCUMENT_BUDGET,
        "amendment_document_budget": AMENDMENT_DOCUMENT_BUDGET,
        "amendment_document_budget_max": AMENDMENT_DOCUMENT_BUDGET_MAX,
        "max_results": STANDARD_RESULT_BUDGET,
    },
    "batch": {
        "recommended_confirmation_minutes": BATCH_RECOMMENDED_CONFIRMATION_MINUTES,
        "checkpoint_retention_days": CHECKPOINT_RETENTION_DAYS,
    },
    "audit": {"enabled": True, "retention_days": AUDIT_RETENTION_DAYS, "audit_query_text": "off"},
    "features": {"dart_fulltext": True, "kind_search": False, "orchestrator": True},
}
